/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited — it is auto-generated by Next.js on startup.
// See https://nextjs.org/docs/app/building-your-application/configuring/typescript
