"""level_1_add_name_type

Revision ID: 159443b72397
Revises: a1b2c3d4e5f6
Create Date: 2026-02-19 21:03:41.312588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '159443b72397'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('number_nodes', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('number_nodes', sa.Column('type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('number_nodes', 'type')
    op.drop_column('number_nodes', 'name')
    # ### end Alembic commands ###
