"""level_4_add_business_logic

Revision ID: 5b3df5b8fe05
Revises: d4e5f6a7b8c9
Create Date: 2026-02-21 11:13:59.879883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3df5b8fe05'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('number_nodes', sa.Column('service_method', sa.String(length=255), nullable=True))
    op.add_column('number_nodes', sa.Column('database_query', sa.Text(), nullable=True))
    op.add_column('number_nodes', sa.Column('external_api_call', sa.String(length=255), nullable=True))
    op.add_column('number_nodes', sa.Column('condition', sa.String(length=500), nullable=True))
    op.add_column('number_nodes', sa.Column('input_schema', sa.JSON(), nullable=True))
    op.add_column('number_nodes', sa.Column('output_schema', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('number_nodes', 'output_schema')
    op.drop_column('number_nodes', 'input_schema')
    op.drop_column('number_nodes', 'condition')
    op.drop_column('number_nodes', 'external_api_call')
    op.drop_column('number_nodes', 'database_query')
    op.drop_column('number_nodes', 'service_method')
    # ### end Alembic commands ###
